
model_dir: "./models/"

data_dir: "./data/"

airport_file: "./data/airports_info.csv"

params:
  name: "dnn_model"
  cells: 1000
  depth: 2
  scale_bool: True
  pca_bool: False
  act: "prelu"
  iterations: 30
  residuals: 2
  sgd_iter: 70
  sgd_lr: 0.01
  sgd_momentum: 0.001
  sgd_decay: 0.001
  sgd_nesterov: True

unseen_length: 100000
