
model_dir: "./models/"

data_dir: "./data/"

name: "dnn_model"

drop_rate: 0.2
filters: 5
kernel_size: 5
act: "prelu"
b_norm: True
cnn_depth: 3
fc_depth: 3
fc_cells: 1000
pool: True
pool_size: 2
